/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serversniffer;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.SwingUtilities;

/**
 *
 * @author David
 */
public class GUI extends javax.swing.JFrame {

    private final DefaultListModel addressesModel;
    private final DefaultListModel possibleModel;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        addressesModel = new DefaultListModel();
        possibleModel = new DefaultListModel();
        lstAddresses.setModel(addressesModel);
        lstPossibleAddresses.setModel(possibleModel);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    }

    public void log(String text) {
        SwingUtilities.invokeLater(() -> {
            txtLog.append(text + "\n");
        });
    }

    public void bar(int value) {
        SwingUtilities.invokeLater(() -> {
            prgBar.setValue(prgBar.getValue() + value);
        });
    }

    public void addAddress(String ip) {
        SwingUtilities.invokeLater(() -> {
            addressesModel.addElement(ip);
            lstAddresses.setModel(addressesModel);
        });
    }

    public void addPossibleAddresses(String ip) {
        SwingUtilities.invokeLater(() -> {
            possibleModel.addElement(ip);
            lstPossibleAddresses.setModel(possibleModel);
        });
    }
    
    public void complete(){
        prgBar.setValue(100);
        txtPort.setEnabled(true);
        txtIterations.setEnabled(true);
        txtTimeout.setEnabled(true);
        lblPort.setEnabled(true);
        lblIterations.setEnabled(true);
        lblTimeout.setEnabled(true);
        btnScan.setEnabled(true);
        btnClear.setEnabled(true);
        panelScan.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScan = new javax.swing.JPanel();
        txtPort = new javax.swing.JTextField();
        lblPort = new javax.swing.JLabel();
        lblIterations = new javax.swing.JLabel();
        txtIterations = new javax.swing.JTextField();
        txtTimeout = new javax.swing.JTextField();
        lblTimeout = new javax.swing.JLabel();
        btnScan = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAddresses = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPossibleAddresses = new javax.swing.JList<>();
        prgBar = new javax.swing.JProgressBar();
        btnClose = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ServerSniffer");
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setResizable(false);

        panelScan.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter New Scan"));
        panelScan.setMaximumSize(new java.awt.Dimension(417, 95));
        panelScan.setMinimumSize(new java.awt.Dimension(417, 95));
        panelScan.setPreferredSize(new java.awt.Dimension(417, 95));

        lblPort.setText("Port:");

        lblIterations.setText("Addresses To Scan:");

        txtTimeout.setText("200");

        lblTimeout.setText("Timeout Value (ms):");

        btnScan.setText("Start Scan");
        btnScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScanActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelScanLayout = new javax.swing.GroupLayout(panelScan);
        panelScan.setLayout(panelScanLayout);
        panelScanLayout.setHorizontalGroup(
            panelScanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelScanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIterations)
                    .addComponent(lblPort)
                    .addComponent(lblTimeout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelScanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimeout)
                    .addComponent(txtPort)
                    .addComponent(txtIterations))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelScanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnScan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        panelScanLayout.setVerticalGroup(
            panelScanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScanLayout.createSequentialGroup()
                .addGroup(panelScanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelScanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIterations)
                    .addComponent(txtIterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelScanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimeout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTimeout)))
            .addGroup(panelScanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnScan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear))
        );

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        lstAddresses.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstAddresses.setMaximumSize(new java.awt.Dimension(1000, 1000));
        lstAddresses.setMinimumSize(new java.awt.Dimension(0, 0));
        lstAddresses.setPreferredSize(new java.awt.Dimension(150, 80));
        jScrollPane1.setViewportView(lstAddresses);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(0, 0));

        lstPossibleAddresses.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstPossibleAddresses.setMaximumSize(new java.awt.Dimension(1000, 1000));
        lstPossibleAddresses.setMinimumSize(new java.awt.Dimension(0, 0));
        lstPossibleAddresses.setPreferredSize(new java.awt.Dimension(150, 80));
        jScrollPane2.setViewportView(lstPossibleAddresses);

        prgBar.setPreferredSize(null);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setRows(5);
        txtLog.setPreferredSize(null);
        jScrollPane3.setViewportView(txtLog);

        jLabel1.setText("Servers-");

        jLabel2.setText("Possible Servers-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelScan, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3)
                        .addComponent(prgBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelScan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prgBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScanActionPerformed
        prgBar.setValue(0);
        txtPort.setEnabled(false);
        txtIterations.setEnabled(false);
        txtTimeout.setEnabled(false);
        lblPort.setEnabled(false);
        lblIterations.setEnabled(false);
        lblTimeout.setEnabled(false);
        btnScan.setEnabled(false);
        btnClear.setEnabled(false);
        panelScan.setEnabled(false);
        txtLog.setText("");
        addressesModel.setSize(0);
        possibleModel.setSize(0);
        lstAddresses.setModel(addressesModel);
        lstPossibleAddresses.setModel(possibleModel);
        repaint();
        int port = Integer.parseInt(txtPort.getText());
        int iterations = Integer.parseInt(txtIterations.getText());
        int timeout = Integer.parseInt(txtTimeout.getText());

        ServerSniffer ss = new ServerSniffer(port, iterations, timeout);
        new Thread(){
            @Override
            public void run() {
                ss.start();
            }
        }.start();
    }//GEN-LAST:event_btnScanActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtPort.setText("");
        txtIterations.setText("");
        txtTimeout.setText("200");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnScan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblIterations;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblTimeout;
    private javax.swing.JList<String> lstAddresses;
    private javax.swing.JList<String> lstPossibleAddresses;
    private javax.swing.JPanel panelScan;
    private javax.swing.JProgressBar prgBar;
    private javax.swing.JTextField txtIterations;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtTimeout;
    // End of variables declaration//GEN-END:variables
}
